name: Release Build

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Upload Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'andrewpwade'

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: |
          npm run lint
          npm run test:ci

      - name: Build extension
        run: |
          mkdir -p dist
          cp manifest.json dist/
          cp content.js dist/
          cp background.js dist/
          cp popup.html dist/
          cp popup.js dist/

      - name: Validate build
        run: |
          if [ ! -f "dist/manifest.json" ]; then
            echo "❌ Build failed: manifest.json missing"
            exit 1
          fi
          echo "✅ Build validation passed"

      - name: Create extension zip
        run: |
          cd dist
          zip -r ../autozoom-${{ github.event.release.tag_name }}.zip .
          cd ..
          ls -la *.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./autozoom-${{ github.event.release.tag_name }}.zip
          asset_name: autozoom-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
